=== bazsa124/IOMAG5_MDBPract/IOMAG5_0225/IOMAG5_XMLSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="etterem" type="etteremType" maxOccurs="unbounded"/>
                <xs:element name="foszakacs" type="foszakacsType" maxOccurs="unbounded"/>
                <xs:element name="szakacs" type="szakacsType" maxOccurs="unbounded"/>
                <xs:element name="gyakornok" type="gyakornokType" maxOccurs="unbounded"/>
                <xs:element name="vendeg" type="vendegType" maxOccurs="unbounded"/>
                <xs:element name="rendeles" type="rendelesType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    
        <xs:key name="etterem_kulcs">
            <xs:selector xpath="etterem"/>
            <xs:field xpath="@eKod" />
        </xs:key>

        <xs:key name="foszakacs_kulcs">
            <xs:selector xpath="foszakacs"/>
            <xs:field xpath="@fKod" />
        </xs:key>

        <xs:key name="szakacs_kulcs">
            <xs:selector xpath="szakacs"/>
            <xs:field xpath="@szKod" />
        </xs:key>

        <xs:key name="gyakornok_kulcs">
            <xs:selector xpath="gyakornok"/>
            <xs:field xpath="@gyKod" />
        </xs:key>

        <xs:key name="vendeg_kulcs">
            <xs:selector xpath="vendeg"/>
            <xs:field xpath="@vKod" />
        </xs:key>

        <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@e_v_e"/>
        </xs:keyref>

        <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@e_v_v"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="foszakacs_etterem_idegen_kulcs">
            <xs:selector xpath="foszakacs"/>
            <xs:field xpath="@e_f"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="szakacs_etterem_idegen_kulcs">
            <xs:selector xpath="szakacs"/>
            <xs:field xpath="@e_sz"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="gyakornok_etterem_idegen_kulcs">
            <xs:selector xpath="gyakornok"/>
            <xs:field xpath="@e_gy"/>
        </xs:keyref>

        <xs:unique name="unique_foszakacs">
            <xs:selector xpath="foszakacs"/>
            <xs:field xpath="@fKod"/>
        </xs:unique>


    </xs:element>

    <xs:complexType name="etteremType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="cimType"/>
            <xs:element name="csillag" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="eKod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="cimType">
        <xs:sequence>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="fKod" type="xs:string" use="required" />
        <xs:attribute name="e_f" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="szakacsType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="reszleg" type="xs:string"/>
            <xs:element name="vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="szKod" type="xs:string" use="required" />
        <xs:attribute name="e_sz" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="gyakornokType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="gyakorlat" type="gyakorlatType"/>
            <xs:element name="muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gyKod" type="xs:string" use="required" />
        <xs:attribute name="e_gy" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="gyakorlatType">
        <xs:sequence>
            <xs:element name="kezdete" type="xs:date"/>
            <xs:element name="idotartam" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

     <xs:complexType name="vendegType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="eletkor" type="xs:integer"/>
            <xs:element name="cim" type="cimType"/>
        </xs:sequence>
        <xs:attribute name="vKod" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="rendelesType">
        <xs:sequence>
            <xs:element name="etel" type="xs:string"/>
            <xs:element name="osszeg" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="e_v_e" type="xs:string" use="required" />
        <xs:attribute name="e_v_v" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== bazsa124/IOMAG5_MDBPract/IOMAG5_0225/IOMAG5_XML.xml
<?xml version="1.0" encoding="UTF-8"?>

    <vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="IOMAG5_XMLSchema.xsd">
        <etterem eKod="e1">
            <nev>Trófea</nev>
            <cim>
                <varos>Budapest</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
            <csillag>3</csillag>
        </etterem>

        <etterem eKod="e2">
            <nev>Leveses</nev>
            <cim>
                <varos>Miskolc</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
            <csillag>5</csillag>
        </etterem>

        <foszakacs fKod="f1" e_f="e1">
            <nev>Teszt Elek</nev>
            <eletkor>67</eletkor>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>gimnazium</vegzettseg>
        </foszakacs>

        <foszakacs fKod="f2" e_f="e2">
            <nev>Piros Alma</nev>
            <eletkor>31</eletkor>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>gimnazium</vegzettseg>
            <vegzettseg>Kulináris egyetem</vegzettseg>
        </foszakacs>

        <szakacs szKod="sz1" e_sz="e1">
            <nev>Kutya Kornél</nev>
            <reszleg>Konyha</reszleg>
            <vegzettseg>8 általános</vegzettseg>
        </szakacs>

        <szakacs szKod="sz2" e_sz="e1">
            <nev>Ötlet Elek</nev>
            <reszleg>Előkészületek</reszleg>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>gimnázium</vegzettseg>
        </szakacs>

        <szakacs szKod="sz3" e_sz="e2">
            <nev>Marha Marcell</nev>
            <reszleg>Előkészületek</reszleg>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>gimnázium</vegzettseg>
            <vegzettseg>Egyetem</vegzettseg>
        </szakacs>

        <gyakornok gyKod="gy1" e_gy="e1">
            <nev>Disznó Dániel</nev>
            <gyakorlat>
                <kezdete>2025-06-01</kezdete>
                <idotartam>90</idotartam>
            </gyakorlat>
            <muszak>2025-06-01 délelőtt</muszak>
            <muszak>2025-06-03 délután</muszak>
        </gyakornok>

        <gyakornok gyKod="gy2" e_gy="e2">
            <nev>Hal Huba</nev>
            <gyakorlat>
                <kezdete>2025-08-01</kezdete>
                <idotartam>120</idotartam>
            </gyakorlat>
            <muszak>2025-08-01 délelőtt</muszak>
            <muszak>2025-08-03 délután</muszak>
        </gyakornok>

        <gyakornok gyKod="gy3" e_gy="e2">
            <nev>Csirke Csilla</nev>
            <gyakorlat>
                <kezdete>2026-01-01</kezdete>
                <idotartam>100</idotartam>
            </gyakorlat>
            <muszak>2026-01-01 délelőtt</muszak>
            <muszak>2026-01-02 délután</muszak>
        </gyakornok>

        <vendeg vKod="v1">
            <nev>Vendég Virág</nev>
            <eletkor>21</eletkor>
            <cim>
                <varos>Eger</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
        </vendeg>

        <vendeg vKod="v2">
            <nev>Eszek Eszter</nev>
            <eletkor>19</eletkor>
            <cim>
                <varos>Győr</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
        </vendeg>

        <rendeles e_v_v="v1" e_v_e="e1">
            <etel>Marha pacal</etel>
            <osszeg>2990</osszeg>
        </rendeles>

        <rendeles e_v_v="v2" e_v_e="e1">
            <etel>Csorba leves</etel>
            <osszeg>1490</osszeg>
        </rendeles>

        <rendeles e_v_v="v2" e_v_e="e2">
            <etel>Disznó pörkölt</etel>
            <osszeg>2790</osszeg>
        </rendeles>

        <rendeles e_v_v="v2" e_v_e="e2">
            <etel>Cézár saláta</etel>
            <osszeg>1890</osszeg>
        </rendeles>

    </vendeglatas>

=== bazsa124/IOMAG5_MDBPract/IOMAG5_0304/XMLDomReader/src/IOMAG5/modifiedIOMAG5.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="IOMAG5_XMLSchema.xsd">
        <etterem eKod="e1">
            <nev>Trófea</nev>
            <cim>
                <varos>Budapest</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
            <csillag>3</csillag>
        </etterem>

        <etterem eKod="e2">
            <nev>Leveses</nev>
            <cim>
                <varos>Miskolc</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
            <csillag>5</csillag>
        </etterem>

        <foszakacs e_f="e1" fKod="f1">
            <nev>Teszt Elek</nev>
            <eletkor>67</eletkor>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>gimnazium</vegzettseg>
        </foszakacs>

        <foszakacs e_f="e2" fKod="f2">
            <nev>Piros Alma</nev>
            <eletkor>31</eletkor>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>gimnazium</vegzettseg>
            <vegzettseg>Kulináris egyetem</vegzettseg>
        </foszakacs>

        <szakacs e_sz="e1" szKod="sz1">
            <nev>Kutya Kornél</nev>
            <reszleg>Konyha</reszleg>
            <vegzettseg>8 általános</vegzettseg>
        </szakacs>

        <szakacs e_sz="e1" szKod="sz2">
            <nev>Ötlet Elek</nev>
            <reszleg>Előkészületek</reszleg>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>gimnázium</vegzettseg>
        </szakacs>

        <szakacs e_sz="e2" szKod="sz3">
            <nev>Marha Marcell</nev>
            <reszleg>Előkészületek</reszleg>
            <vegzettseg>8 általános</vegzettseg>
            <vegzettseg>Orbán Viktor Szakközépiskola</vegzettseg>
            <vegzettseg>Egyetem</vegzettseg>
        </szakacs>

        <gyakornok e_gy="e1" gyKod="gy1">
            <nev>Disznó Dániel</nev>
            <gyakorlat>
                <kezdete>2025-06-01</kezdete>
                <idotartam>90</idotartam>
            </gyakorlat>
            <muszak>2025-06-01 délelőtt</muszak>
            <muszak>2025-06-03 délután</muszak>
        </gyakornok>

        <gyakornok e_gy="e3" gyKod="gy2">
            <nev>Hal Huba</nev>
            <gyakorlat>
                <kezdete>2025-08-01</kezdete>
                <idotartam>120</idotartam>
            </gyakorlat>
            <muszak>2025-08-01 délelőtt</muszak>
            <muszak>2025-08-03 délután</muszak>
        </gyakornok>

        <gyakornok e_gy="e2" gyKod="gy3">
            <nev>Csirke Csilla</nev>
            <gyakorlat>
                <kezdete>2026-01-01</kezdete>
                <idotartam>100</idotartam>
            </gyakorlat>
            <muszak>2026-01-01 délelőtt</muszak>
            <muszak>2026-01-02 délután</muszak>
        </gyakornok>

        <vendeg vKod="v1">
            <nev>Alma Palma</nev>
            <eletkor>25</eletkor>
            <cim>
                <varos>Eger</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
        </vendeg>

        <vendeg vKod="v2">
            <nev>Eszek Eszter</nev>
            <eletkor>19</eletkor>
            <cim>
                <varos>Győr</varos>
                <utca>Alma</utca>
                <hazszam>1</hazszam>
            </cim>
        </vendeg>

        

        

        

        

    </vendeglatas>
